### ISSUE TITLE
Cant do anything

### ISSUE THREAD

**Issue by pective** [nethical6/digipaws#48]
I selected adventure mode and now when i open the app it just closes. Occasionally it shows me the accessibility permission disclosure, but i cant do anything from there, cuz i cant access the app's settings menu

**Comment by nethical6** [comment]
I'm so sorry.
all of these bugs have been fixed in the kotlin rewrite which I'll be releasing this week. 

if you've got your phone stuck in anti-uninstall. You can remove it either by putting your phone into safe mode or if you can access device settings, try changing the device time to a month ahead and you should be able to uninstall the app.

**Comment by pective** [comment]
Thanks for the blazingly fast reply man, i'll try changing my date and i'll try the app out once again when the rewrite releases, cheers!

**Comment by pective** [comment]
Yeah it worked, thanks for the help. I'll close the issue as the problem is solved.
